### ISSUE TITLE
Check duplicate titles in canMerge

### ISSUE THREAD

**Issue by kirderf1** [lunar-sway/minestuck#105]
Right now titles aren't checked when merging two sessions. This requires changes in both SessionHandler.canMerge() and SessionHandler.canMergeAll()

**Comment by BenjaminKirksey** [comment]
What behavior should occur instead?

**Comment by kirderf1** [comment]
The two can merge methods should check for any duplicate titles in the afflicted sessions, and if it does find any collisions, the whole method should return false.

**Comment by kirderf1** [comment]
Restrictions on sessions is softening up with #545, which I think removes the desire to have this check.
